### ISSUE TITLE
Feature Request: Specifying multiple metrics for file

### ISSUE THREAD

**Issue by shyamupa** [wikilinks/neleval#21]
Usually people care about CEAFe, MUC, PW and B3 for general coreference problems.
Currently, if I do not specify anything,

```
../neleval/nel evaluate -g gold/gold.file -f tab pred.file
```

I get a lot of output, which I really do not care about. On the other hand, I can specify,

```
../neleval/nel evaluate -g gold/gold.file -f tab pred.file -m muc
```

which gives me only one. Maybe there should be a way to specify multiple metrics 
```
-m muc,b_cubed,pairwise
``` 

Or have a flag for printing the common metrics?

**Comment by jnothman** [comment]
There is. From `nel evaluate --help`:   -m NAME, --measure NAME Which measures to use: specify a name (or group name) from the list-measures command. **This flag may be repeated.**

```
../neleval/nel evaluate -g gold/gold.file -f tab pred.file -m muc -m b_cubed -m pairwise
```

 Please let me know if there's some better way of documenting this than the current.
