### ISSUE TITLE
Entity CEAF true positives and false positives off by factor of 2. 

### ISSUE THREAD

**Issue by cpalenmichel** [wikilinks/neleval#29]
I believe there is a 2 missing in the definition of the dice coefficient which causes the true positives and false positives to be off by a factor of 2. 
Line 343 of https://github.com/wikilinks/neleval/blob/master/neleval/coref_metrics.py
Luckily this doesn't affect precision, recall or F-score since everything ends up off by a factor of two, so the issue is definitely not urgent, but should be an easy fix. 

My understanding of CEAF is based on what I read in http://www.aclweb.org/anthology/H05-1004. On page 28 they define the similarity metrics. It's also possible I've misunderstood how this metric is calculated. If that's the case,  kindly let me know.

**Comment by jnothman** [comment]
Thanks, I think you're right.

**Comment by jnothman** [comment]
We've always tested on the basis of P, R, F so it's not surprising this was
missed. Would you like to offer a Pull Request to patch both dice and
_vectorized_dice?
If not, I'll do it, but let me know. Thanks.

**Comment by cpalenmichel** [comment]
Sorry for the delay. Should be fixed here https://github.com/wikilinks/neleval/pull/32
